In [1]:
import tensorflow as tf
print(tf.__version__)

2.0.0


In [2]:
# load dataset
mnist = tf.keras.datasets.fashion_mnist

In [3]:
# split dataset into train and test
(training_images, training_labels), (test_images, test_labels) = mnist.load_data()

In [4]:
# display the clothes image of train and test data
import numpy as np
np.set_printoptions(linewidth=200)
import matplotlib.pyplot as plt
plt.imshow(training_images[0])
print(training_labels[0])
print(training_images[0])

9
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   1   0   0  13  73   0   0   1   4   0   0   0   0   1   1   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3   0  36 136 127  62  54   0   0   0   1   3   4   0   0   3]
 [  0   0   0   0   0   0   0   0   0   0   0   0   6   0 102 204 176 134 144 123  23   0   0   0   0  12  10   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0 155 236 207 178 107 156 161 109  64  23  77 130  72  15]
 [  0   0   0   0   0   0   0   0   0   0   0   1   0  69 207 223 218 216 216 163 127 121 122 146 141  88 172  66]
 [  0   0   0   0   0   0   0   0   0   1   1   1   0 200 232 232 233 229 223 

In [5]:
# normalize the image pixel values 
training_images  = training_images / 255.0
test_images = test_images / 255.0

In [6]:
# define the model layers
model = tf.keras.models.Sequential([tf.keras.layers.Flatten(), 
                                    tf.keras.layers.Dense(128, activation=tf.nn.relu), 
                                    tf.keras.layers.Dense(10, activation=tf.nn.softmax)])

In [7]:
# compile and fit the dataset to model
model.compile(optimizer = tf.optimizers.Adam(),
              loss = 'sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(training_images, training_labels, epochs=20)

Train on 60000 samples
Epoch 1/20
60000/60000 [==============================] - 7s 123us/sample - loss: 0.4975 - accuracy: 0.8258
Epoch 2/20
60000/60000 [==============================] - 9s 154us/sample - loss: 0.3747 - accuracy: 0.8648
Epoch 3/20
60000/60000 [==============================] - 6s 101us/sample - loss: 0.3380 - accuracy: 0.8780
Epoch 4/20
60000/60000 [==============================] - 7s 114us/sample - loss: 0.3137 - accuracy: 0.8852
Epoch 5/20
60000/60000 [==============================] - 7s 111us/sample - loss: 0.2948 - accuracy: 0.8907
Epoch 6/20
60000/60000 [==============================] - 7s 110us/sample - loss: 0.2798 - accuracy: 0.8971
Epoch 7/20
60000/60000 [==============================] - 8s 133us/sample - loss: 0.2674 - accuracy: 0.9004
Epoch 8/20
60000/60000 [==============================] - 7s 111us/sample - loss: 0.2575 - accuracy: 0.9044
Epoch 9/20
60000/60000 [==============================] - 6s 98us/sample - loss: 0.2492 - accuracy: 0.9069
Epoch 

In [8]:
# evaluate the model with test data
model.evaluate(test_images, test_labels)

10000/1 [===============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[0.3604244553089142, 0.8877]

In [9]:
# predict the classes
classifications = model.predict(test_images)
# predicted class
print(classifications[0])

[6.97177602e-12 3.96337531e-13 3.20674182e-11 9.23843078e-19 1.40427047e-12 2.99506482e-05 1.07467785e-10 1.40974546e-04 4.94880525e-12 9.99829054e-01]


In [10]:
# actual class of test data first image
print(test_labels[0])

9


In [11]:
# call back function
class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs={}):
    if(logs.get('loss')<0.3):
      print("\nReached 60% accuracy so cancelling training!")
      self.model.stop_training = True

callbacks = myCallback()

In [12]:
# call the callback function when reach the required accuracy
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(512, activation=tf.nn.relu),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy')
model.fit(training_images, training_labels, epochs=5, callbacks=[callbacks])

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 14s 227us/sample - loss: 0.4712
Epoch 2/5
60000/60000 [==============================] - 14s 240us/sample - loss: 0.3574
Epoch 3/5
60000/60000 [==============================] - 17s 279us/sample - loss: 0.3235
Epoch 4/5
59936/60000 [============================>.] - ETA: 0s - loss: 0.2996
Reached 60% accuracy so cancelling training!
60000/60000 [==============================] - 17s 288us/sample - loss: 0.2997


In [13]:
print(model.predict_classes(test_images))

[9 2 1 ... 8 1 5]


In [14]:
print(test_labels)

[9 2 1 ... 8 1 5]


#### With this we can classify the clothes of different classes from 0 to 9. Similar model can be used for multi class classification problem of computer vision.